update calculix to 2.17
waebbl/waebbl-gentoo pull request #318
Opened 2021-05-25 09:56 UTC by galanom

This are the ebuilds and patches for current version, 2.17, of calculix-ccx and calculix-cgx.
I used the master branch files of version 2.10 as a template. I did not alter any DEPEND variable.
It works for me and I hope it might be useful for others.

2021-05-25 17:34 UTC, waebbl commented
Thanks for your contribution! Long time since I last checked that package... Glad someone noticed the updated package :)

The code in the ebuilds is quite old and from the time, when I began writing ebuilds. As such it could use some improvements.
Would you be willing to participate in a review of the code and improve it to adhere current ebuild standard?
It's ok, if you don't want to do this, I then do it myself.

2021-05-28 08:01 UTC, galanom commented
Hello,
I'll be happy to help if I can, but keep in mind I've never written an ebuild.
If there is a resource describing the changes you need, please let me know.

2021-05-28 11:26 UTC, waebbl commented
@galanom That's ok. I will start a review process and we will together go through the code.
Resources which might be useful are the devmanual: https://devmanual.gentoo.org/index.html which contains a host of information about writing ebuilds. More technical and theoretical and probably less useful at this time is the PMS: https://dev.gentoo.org/~ulm/pms/head/pms.html

Of some importance, however, is, before commiting your changes, please run `repoman -dx manifest` to update the Manifest and `repoman -dx full` to check the ebuilds. Also please run `pkgcheck scan .` in the ebuild directory.

2021-05-28 11:42 UTC, waebbl requested changes
Could you please try to fix these?

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-ccx/calculix-ccx-2.17.ebuild
> +# Distributed under the terms of the GNU General Public License v2
Please update the last copyright year. Should look like `1999-2021`

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-ccx/calculix-ccx-2.17.ebuild
> +inherit eutils toolchain-funcs flag-o-matic fortran-2
Is eutils still needed?

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-ccx/calculix-ccx-2.17.ebuild
> +HOMEPAGE="http://www.calculix.de/"
Could you please check if https is working for the homepage?

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-ccx/calculix-ccx-2.17.ebuild
> +	examples? ( http://www.dhondt.de/${MY_P}.test.tar.bz2 )"
Same here

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-ccx/calculix-ccx-2.17.ebuild
> +	doc? ( app-text/ghostscript-gpl )"
`virtual/pkgconfig` and the dependency for the `doc` use flag are both build time dependencies. They now belong to the `BDEPEND` variable.
The `DEPEND` line should just read `DEPED="${RDEPEND}"` here

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-ccx/calculix-ccx-2.17.ebuild
> +S=${WORKDIR}/CalculiX/${MY_P}/src
Nowadays, the `S` entry goes in the description block above. Please move it just beyond the `SRC_URI` variable.

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-cgx/calculix-cgx-2.17.ebuild
> +# Copyright 1999-2018 Gentoo Authors
Please adjust copyright year here too

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-cgx/calculix-cgx-2.17.ebuild
> +	doc? ( http://www.dhondt.de/${MY_P}.pdf )"
Same as with calculix-ccx: please check for https availability

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-cgx/calculix-cgx-2.17.ebuild
> +	x11-libs/libICE:="
None of these dependencies actually needs the slot operator (`:=`). Please remove it from all of them.

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-cgx/calculix-cgx-2.17.ebuild
> +	doc? ( app-text/ghostscript-gpl )"
Same as with calculix-ccx: the `doc` line belongs to `BDEPEND`.

2021-05-28 11:42 UTC, waebbl commented on sci-libs/calculix-cgx/calculix-cgx-2.17.ebuild
> +S=${WORKDIR}/CalculiX/${MY_P}/src/
Please move to the description, homepage block above.

2021-06-09 17:11 UTC, galanom commented
Hello,
Thanks for taking the time to help me, and I'm sorry for late reply!
Regarding the changes requested:
a) I see that https does not seem to work, therefore no changes made to URLs
b) All RDEPENDs of calculix-cgx are not slotted, therefore I removed the ":=" from all of them, not just libXext, libXt, libSM, libICE
I believe new commit is automatically visible, please tell me if you need further changes.

2021-06-09 19:00 UTC, waebbl commented
> Thanks for taking the time to help me, and I'm sorry for late reply!

You're welcome. Help with package maintainance on Gentoo systems is always needed :)
Don't worry about long reply times, there's no need to hurry. I find it more important to get some quality than to get it done fast.

> Regarding the changes requested:
> a) I see that https does not seem to work, therefore no changes made to URLs

That's ok. I just didn't know. We can't do anything about it anyway.

> b) All RDEPENDs of calculix-cgx are not slotted, therefore I removed the ":=" from all of them, not just libXext, libXt, libSM, libICE

It's perfect for the dependencies used in the ebuild.
But note, that not only the slot is important, but also subslots, i.e. slots in the form of e.g. `0/27`, i.e. two slot identifiers divided by slash sign. If a package has just one slot, but uses subslots, then the slot operator is also needed to properly trigger automatic rebuild of revdeps. It doesn't apply here though.

> I believe new commit is automatically visible, please tell me if you need further changes.

The ebuilds look good to me. I'm going to test them and merge if they work.

2021-06-13 08:58 UTC, waebbl commented
There's an issue with the calculix-cgx ebuild with USE=doc. The pdf file doesn't get unpacked, because the unpacker doesn't know how to handle PDF files. For this, a src_unpack function needs to be implemented. I'm going to do this myself. Anything else is working.
Thanks for your contribution.

2021-06-13 08:58 UTC, merged